- type: basic
  topic: /dps310_2/data
  folder: dps310_2_data
  extension: csv

- type: basic
  topic: /dps310_sphere/data
  folder: dps310_sphere_data
  extension: csv
  
- type: basic
  topic: /setra/pressure
  folder: setra_pressure
  extension: csv

- type: basic
  topic: /mcp9808/temperature
  folder: mcp9808_temperature
  extension: csv
