- type: basic
  topic: /dps310_1/temperature
  folder: dps310_1_temperature

- type: basic
  topic: /dps310_1/pressure
  folder: dps310_1_pressure

- type: basic
  topic: /dps310_2/temperature
  folder: dps310_2_temperature

- type: basic
  topic: /dps310_2/pressure
  folder: dps310_2_pressure

- type: basic
  topic: /setra/pressure
  folder: setra_pressure

- type: basic
  topic: /mcp9808/temperature
  folder: mcp9808_temperature
