- type: basic
  topic: /motors/left/encoder
  folder: left_encoder

- type: basic
  topic: /motors/right/encoder
  folder: right_encoder

- type: basic
  topic: /motors/left/electrical
  folder: left_electrical

- type: basic
  topic: /motors/right/electrical
  folder: right_electrical

- type: odometry
  topic: /icp_odom
  folder: icp_odom
  args:
    euler: true

- type: odometry
  topic: /motors/odometry
  folder: wheel_odom
  args:
    euler: true

- type: odometry
  topic: /imu_and_wheel_odom
  folder: imu_and_wheel_odom
  args:
    euler: true

- type: image
  topic: /zed_node/left_raw/image_raw_color
  folder: camera_left
  args:
    extension: png
    rectify: true
    scale: 1.0
    gray_scale: false

- type: image
  topic: /zed_node/right_raw/image_raw_color
  folder: camera_right
  args:
    extension: png
    rectify: true
    scale: 1.0
    gray_scale: false

- type: point_cloud
  topic: /lslidar_point_cloud
  folder: lidar

- type: audio
  topic: /audio/audio_stamped
  folder: audio
  args:
    extension: wav
    sample_rate: 44100

- type: imu
  topic: /MTI_imu/data
  folder: imu
  args:
    euler: true
