- type: gnss
  topic: /emlid/front/fix
  folder: gnss_1

- type: gnss
  topic: /emlid/left/fix #middle = left
  folder: gnss_2

- type: gnss
  topic: /emlid/right/fix #back = right
  folder: gnss_3

- type: odometry
  topic: /mapping/icp_odom
  folder: icp_odom
  args: 
    euler: false