- type: odometry
  topic: /mapping/icp_odom
  folder: icp_odom
  args:
    euler: true

- type: odometry
  topic: /warthog_velocity_controller/odom
  folder: wheel_odom
  args:
    euler: true

- type: odometry
  topic: /reachrs/tessellate/odom
  folder: rtk_odom
  args:
    euler: true

- type: imu
  topic: /mti30/data
  folder: imu
  args:
    euler: true

- type: image
  topic: /zed_node/left_raw/image_raw_color
  folder: ground/images
  args:
    extension: png
    rectify: false
    scale: 1.0
    gray_scale: false

- type: basic
  topic: /battery_logs
  folder: power

- type: audio
  topic: /audio/left_mic
  folder: audio_left
  args:
    extension: wav
    sample_rate: 44100

- type: audio
  topic: /audio/right_mic
  folder: audio_right
  args:
    extension: wav
    sample_rate: 44100
